
version: "3.7"
services:
  bladegps:
    build:
      context: .
    cap_add:
    - ALL
    command: bladegps -e /opt/bladeGPS/brdc3300.18n -l 35.274,137.014,100 -d 86400
    container_name: bladegps
    devices:
    - /dev/ttyUSB0
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 10m
    restart: always
